name: Android 9 Emulator (Nexus 5)

on:
  workflow_dispatch:

permissions:
  contents: write   # cần cho git push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check Docker
        run: docker --version

      - name: Start Android 9 Nexus 5
        run: |
          docker run -d --name android -p 6080:6080 -p 5554:5554 -p 5555:5555 \
            -e DEVICE="Nexus 5" \
            -e ANDROID_VERSION=9.0 \
            -e APPIUM=false \
            budtmo/docker-android-x86-9.0

      - name: Start Cloudflare Tunnel
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          ./cloudflared tunnel --url http://localhost:6080 --no-autoupdate > tunnel.log 2>&1 &
          sleep 10
          grep -o 'https://.*trycloudflare.com' tunnel.log > remote.txt
          cat remote.txt

      - name: Commit remote.txt to repo
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add remote.txt
          git commit -m "Update remote.txt with Cloudflare URL"
          git push

      - name: Keep Alive (6h)
        run: |
          echo "Emulator running. Keeping alive for 6 hours..."
          for i in {1..2160}; do
            echo "tick $i"
            sleep 10
          done
