name: Android Emulator (Nexus 5 - Android 9)

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start Android 9 Nexus 5
        run: |
          docker run -d --name android -p 6080:6080 \
            -e DEVICE="Nexus 5" \
            -e EMULATOR="emulator" \
            -e APPIUM="false" \
            -e MOBILE_WEB_TEST="false" \
            -e AUTO_RECORD="false" \
            budtmo/docker-android:emulator_9.0

      - name: Start Cloudflare Tunnel
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          ./cloudflared tunnel --url http://localhost:6080 --no-autoupdate > tunnel.log 2>&1 &
          sleep 10
          grep -o "https://[-0-9a-z]*\.trycloudflare.com" tunnel.log | head -n1 > url.txt
          cat url.txt

      - name: Recheck origin via tunnel
        run: curl -I $(cat url.txt)

      - name: Commit remote.txt to repo
        run: |
          echo "🔗 Access Emulator at:" > remote.txt
          cat url.txt >> remote.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add remote.txt
          git commit -m "Add emulator link"
          git push
